import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:intl/intl.dart';
import 'package:moticar/widgets/app_texts.dart';

import '../../models/expensesmodel.dart';
import '../../widgets/colors.dart';
import 'car_parts3.dart';

class ConfirmImage extends StatefulWidget {
  const ConfirmImage({
    super.key,
    required this.carParts,
    required this.partImage,
    required this.partCategory,
    required this.productName,
    required this.brand,
    required this.quantity,
    required this.condition,
    required this.description,
    required this.amount,
    required this.measurements,
  });
  final String carParts,
      partImage,
      partCategory,
      productName,
      brand,
      condition,
      description,
      amount,
      measurements;

  final int quantity;
  // final List<Carpart> carparts;

  @override
  State<ConfirmImage> createState() => _ConfirmImageState();
}

class _ConfirmImageState extends State<ConfirmImage> {
  final NumberFormat nairaFormat = NumberFormat.currency(
    symbol: 'N ', //₦
    // decimalDigits: 0,
    locale: 'en_NG',
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xffB8F2F4),
      body: SingleChildScrollView(
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 2, horizontal: 2),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Padding(
                padding: const EdgeInsets.all(15.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    IconButton(
                        onPressed: () {
                          Navigator.pop(context);
                        },
                        icon: const Icon(Icons.close_rounded))
                  ],
                ),
              ),

              Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Padding(
                    padding: EdgeInsets.only(left: 15.0, right: 15),
                    child: GestureDetector(
                      onTap: () {
                        Navigator.pop(context);
                      },
                      child: Text(
                        "Please confirm this is what the car part looks like",
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          fontFamily: "NeulisAlt",
                          fontWeight: FontWeight.w600,
                          fontSize: 18,
                          color: AppColors.textColor,
                        ),
                      ),
                    ),
                  ),

                  Padding(
                    padding: const EdgeInsets.only(
                        top: 15.0, left: 30, right: 30, bottom: 15),
                    child: Container(
                      // height: 200,
                      // width: double.infinity,
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(20),
                      ),
                      padding: const EdgeInsets.all(8),
                      alignment: Alignment.center,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          Image.asset(
                            "assets/images/sample_litre.png",
                            height: 200,
                          ),
                          const Text(
                            "Image generated by AI",
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontFamily: "NeulisAlt",
                              fontWeight: FontWeight.w400,
                              fontSize: 10,
                              color: AppColors.textGrey,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  //change image by ai
                  Padding(
                    padding: const EdgeInsets.only(left: 45.0, right: 45),
                    child: Container(
                      // height: 50,
                      // width: 80,
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: const Color(0xffF8E761),
                        borderRadius: BorderRadius.circular(32),
                      ),
                      child: const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.cached, color: AppColors.lightGreen),
                          SizedBox(width: 8),
                          Text(
                            "Show me another image sample",
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontFamily: "NeulisAlt",
                              fontWeight: FontWeight.bold,
                              fontSize: 12,
                              color: Color(0xff002D36),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  //title
                  const Padding(
                    padding: EdgeInsets.all(20.0),
                    child: Text(
                      'The image is just an example. It doesn’t have to be this color, shade or car look alike.',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontFamily: "NeulisAlt",
                        fontSize: 14,
                        fontWeight: FontWeight.w400,
                        color: AppColors.appThemeColor,
                      ),
                    ),
                  ),
                ],
              ),

              SizedBox(height: 10),

              //strike
              Padding(
                padding: const EdgeInsets.all(12.0),
                child: MoticarLoginButton(
                  borderColor: const Color(0xff00343F),
                  myColor: const Color(0xff00343F),
                  child: const Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        'Yes, it is',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          fontFamily: 'NeulisAlt',
                          color: AppColors.white,
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                  onTap: () {
                    Navigator.push(context, MaterialPageRoute(
                      builder: (context) {
                        return AddCarPart3(
                          carParts: widget.carParts,
                          partImage: widget.partImage,
                          partCategory: widget.partCategory,
                          productName: widget.productName,
                          brand: widget.brand.toString(),
                          condition: widget.condition,
                          quantity: widget.quantity,
                          description: widget.description,
                          amount: widget.amount,
                          measurements: widget.measurements,
                        );
                      },
                    ));
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  double calculateTotalExpense(List<Carpart> expenses) {
    double total = 0;
    for (var expense in expenses) {
      total += double.parse(expense.total);
    }
    return total;
  }

  Color getImageColor(String category) {
    switch (category) {
      case 'Body works':
        return AppColors.anotherYellow; // Set color for bodywork category
      case 'Engine':
        return AppColors.diaColor; // Set color for engine category
      case 'Servicing':
        return const Color(0xff006C70);
      case 'Keywork':
        return AppColors.yellow;
      case 'Balancing':
      case 'Car Wash':
        return const Color(0xff00AEB5);
      case 'Dues':
        return const Color(0xff00AEB5);

      case 'Electronics':
        return const Color(0xff00AEB5);
      case 'Fuel':
        return const Color(0xffB8F2F4);
      case 'Hydraulics':
        return const Color(0xff00AEB5);
      case 'Alignment':
        return const Color(0xff29D7DE);

      case 'Tyre':
        return AppColors.textGrey;
      default:
        return AppColors
            .skipColor; // Default color if no specific color is available
    }
  }

  //images based on category
  Widget getImageWidget(String category) {
    switch (category) {
      case 'Body works':
        return SvgPicture.asset(
          'assets/expenseCatIcons/bodywork.svg',
        );
      case 'Engine':
        return SvgPicture.asset('assets/expenseCatIcons/engine.svg');

      case 'Tyre Guage':
        return SvgPicture.asset('assets/expenseCatIcons/tyreGuage.svg');

      case 'Balancing':
        return SvgPicture.asset('assets/expenseCatIcons/balancing.svg');

      case 'Car Wash':
        return SvgPicture.asset('assets/expenseCatIcons/carWash.svg');

      case 'Dues':
        return SvgPicture.asset('assets/expenseCatIcons/dues.svg');

      case 'Electronics':
        return SvgPicture.asset('assets/expenseCatIcons/electronics.svg');

      case 'Fuel':
        return SvgPicture.asset('assets/expenseCatIcons/fuel.svg');

      case 'Hydraulics':
        return SvgPicture.asset('assets/expenseCatIcons/hydraulic.svg');

      case 'Keywork':
        return SvgPicture.asset('assets/expenseCatIcons/keywork.svg');

      case 'Mechanical':
        return SvgPicture.asset('assets/expenseCatIcons/mechanicalWork.svg');

      case 'Misc':
        return SvgPicture.asset('assets/expenseCatIcons/misc.svg');

      case 'Parking':
        return SvgPicture.asset('assets/expenseCatIcons/parking.svg');

      case 'Penalty':
        return SvgPicture.asset('assets/expenseCatIcons/penalty.svg');

      case 'Radiator':
        return SvgPicture.asset('assets/expenseCatIcons/radiator.svg');

      case 'Servicing':
        return SvgPicture.asset('assets/expenseCatIcons/servicing.svg');

      case 'Tow':
        return SvgPicture.asset('assets/expenseCatIcons/tow.svg');

      case 'Tyre guage':
        return SvgPicture.asset('assets/expenseCatIcons/tyreGuage.svg');
      // Add more cases for other categories if needed
      default:
        // Return a default image or null if no specific image is available
        return SvgPicture.asset("assets/expenseCatIcons/alignment.svg");
    }
  }

//carpart images
  Widget getCarParts(String category) {
    switch (category) {
      case 'Brake pad':
        return SvgPicture.asset(
          'assets/carPartsIcons/brakes.svg',
        );

      case 'Tyre':
        return SvgPicture.asset(
          'assets/carPartsIcons/tyres.svg',
        );
      //
      case 'Air Conditioning':
        return SvgPicture.asset(
          'assets/carPartsIcons/Air Conditioning.svg',
        );
      case 'Auto Car Care':
        return SvgPicture.asset(
            'assets/carPartsIcons/autodetailingCarCare.svg');

      case 'Bearing':
        return SvgPicture.asset('assets/carPartsIcons/bearings.svg');

      case 'Belts Chains':
        return SvgPicture.asset('assets/carPartsIcons/BeltsChainsRollers.svg');

      case 'Body':
        return SvgPicture.asset('assets/carPartsIcons/body.svg');

      case 'Brakes':
        return SvgPicture.asset('assets/carPartsIcons/brakes.svg');

      case 'Car Accessories':
        return SvgPicture.asset('assets/carPartsIcons/carAccessories.svg');

      case 'Clutch':
        return SvgPicture.asset('assets/carPartsIcons/clutch.svg');

      case 'Damping':
        return SvgPicture.asset('assets/carPartsIcons/Damping.svg');

      case 'Drive Shaft':
        return SvgPicture.asset('assets/carPartsIcons/driveShaftCVJoint.svg');

      case 'Electrics':
        return SvgPicture.asset('assets/carPartsIcons/electrics.svg');

      case 'Engine oil':
        return SvgPicture.asset('assets/carPartsIcons/engine.svg');

      // case 'Engine':
      // return SvgPicture.asset('assets/carPartsIcons/engine.svg');

      case 'Engine Cooling System':
        return SvgPicture.asset('assets/carPartsIcons/EngineCoolingSystem.svg');

      case 'Exhaust':
        return SvgPicture.asset('assets/carPartsIcons/exhaust.svg');

      case 'Fastners':
        return SvgPicture.asset('assets/carPartsIcons/fastners.svg');

      case 'Filters':
        return SvgPicture.asset('assets/carPartsIcons/filters.svg');

      // case 'Engine Cooling System':
      //   return SvgPicture.asset('assets/carPartsIcons/fuelSupplySystem.svg');

      case 'Gasket':
        return SvgPicture.asset('assets/carPartsIcons/gasket.svg');

      //ignition
      case 'Ignition':
        return SvgPicture.asset(
            'assets/carPartsIcons/ignitionPreheatingSystem.svg');

      //interior
      case 'Interior':
        return SvgPicture.asset(
            'assets/carPartsIcons/ignitionPreheatingSystem.svg');

      //light
      case 'Lighting':
        return SvgPicture.asset('assets/carPartsIcons/lighting.svg');

      // Add more cases for other categories if needed
      default:
        // Return a default image or null if no specific image is available
        return SvgPicture.asset("assets/carPartsIcons/body.svg");
    }
  }
}
